### ISSUE TITLE
Can we get the ISBN number scraped as well?

### ISSUE THREAD

**Issue by paulito415** [doitlikejustin/amazon-wish-lister#10]
Hi Justin,

Thanks for the great tool! Is it possible to add ISBN (10 and 13) to the list of properties returned in the JSON?

Thanks,
Paul

**Comment by mcilroyc** [comment]
+1 for this idea.  My guess is that you would have to loop over each result individually and make a separate screen-scrape of the `link` to grab ISBN from that page.  Sound right?  Maybe there is an existing project that already does such a page scrape that we could leverage?  Anyone familiar with something?  I'm not a PHP guy but I might be able to hack my way through it - if this idea is not crazy.

**Comment by AntoniosHadji** [comment]
i did some research on looking up ISBN and it appears that the Amazon Products API is required.  The results I achieved showed quite a few results coming back without ISBN numbers.  

Here is a snippet of the python code I created to test.
```python
def retrieve_isbn(asin_list):
    '''
    take list of ASIN numbers
    connect to Amazon Product API
    to retrieve ItemAttributes Response Group
    extract ISBN number
    return list of ISBN
    '''
    isbn_list = []
    no_isbn = []
    amazon = bottlenose.Amazon(aws_config.AWS_ACCESS_KEY_ID,
                               aws_config.AWS_SECRET_ACCESS_KEY,
                               aws_config.AWS_ASSOCIATE_TAG,
                               MaxQPS=0.9)
    pattern = re.compile(r'ISBN>(\w{10,13})<\/E?ISBN>')
    ctr = 0
    for asin in asin_list:
        ctr += 1
        response = amazon.ItemLookup(ItemId=asin,
                                     ResponseGroup='ItemAttributes')
        match = pattern.search(response)
        if match:
            isbn_list.append(match.group(1))
            print("num:{} ISBN: {}".format(ctr, match.group(1)))
        else:
            no_isbn.append(asin)

    write_list_to_file("no_reference.txt", no_isbn)
    return isbn_list
```

**Comment by edent** [comment]
#17 retrieves the AISN.  Where the item is a book, the AISN will be the same as the ISBN.

https://en.wikipedia.org/wiki/Amazon_Standard_Identification_Number

**Comment by mcilroyc** [comment]
nice work @edent, thanks
