### ISSUE TITLE
Safety issues

### ISSUE THREAD

**Issue by kthacker7** [doitlikejustin/amazon-wish-lister#22]
Hi Justin,
I plan on running this script on AWS and use this as a backend for an iOS app which uses a user's wishlist. Can you tell me about the potential legal issues and if I could get IP banned for using this screen scraping tool?

Sorry I put this as an issue, I didn't know how else I could comment.

**Comment by doitlikejustin** [comment]
I would check this out https://www.quora.com/Internet-Law-What-is-the-legality-of-web-scraping-public-Amazon-wishlists-with-the-intention-of-recommending-those-products-to-friends-and-family-as-gift-suggestions-and-making-money-from-affiliate-sales-on-Amazon-and-other-online-stores

**Comment by kthacker7** [comment]
Awesome, thanks a lot!
