### ISSUE TITLE
Can't find package on composer

### ISSUE THREAD

**Issue by jmwri** [doitlikejustin/amazon-wish-lister#23]
I am trying to use this package but can't find it on composer, is it on there?

If not is it a possibility that it could be added?

**Comment by jmwri** [comment]
Just found [this pull request](https://github.com/doitlikejustin/amazon-wish-lister/pull/19). Any chance this could be merged?

**Comment by doitlikejustin** [comment]
Updated

**Comment by jmwri** [comment]
Would you be able to add the project to [packagist](https://packagist.org/)?
