### ISSUE TITLE
My ID Returns "null"

### ISSUE THREAD

**Issue by openexcel** [doitlikejustin/amazon-wish-lister#9]
Your ID works fine:
http://www.justinscarpetti.com/projects/amazon-wish-lister/api/?id=37XI10RRD17X2
but mine returns a "null"
http://www.justinscarpetti.com/projects/amazon-wish-lister/api/?id=AT9ERHVAMVGT5

I followed you instructions from your page (http://www.justinscarpetti.com/projects/amazon-wish-lister) but my user ID did not show.
So, I went to my Profile (http://www.amazon.com/gp/pdp/profile/AT9ERHVAMVGT5) and took the 13 digit number
Q: Does the ID have to be a Seller ID or can it be a standard buyer ID?
I tried to see what would happen if I switched out my ID with your in the profile http://www.amazon.com/gp/pdp/profile/37XI10RRD17X2 and it took me to an error page
Thanks for any help!

**Comment by doitlikejustin** [comment]
UK Amazon support has now been added
